---
# This role deploys the mongod processes and sets up the replication set.

- name: create data directory for mongodb
  file: path={{ansible_env.HOME}}/data/{{ item.name }} state=directory
  with_items: 
    - "{{ mongo_repl_set_list }}"

#- name: create log directory for mongodb
#  file: path=/var/log/mongo state=directory owner=mongodb group=mongodb

#- name: create run directory for mongodb
#  file: path=/var/run/mongo state=directory owner=mongod group=mongod

#- name: Create the mongodb startup file
#  template: src=mongod.j2 dest=/etc/init.d/mongod-{{ inventory_hostname }} mode=0655
#  delegate_to: '{{ item }}'
#  with_items: groups.replication_servers

#- name: print db path
#  debug: var={{ mongo_db_path }}

- name: Create the mongodb configuration file
  template: src=mongod.conf.j2 dest=/etc/mongod-{{ item.name }}.conf
  with_items: 
    - "{{ mongo_repl_set_list }}"
  sudo: True

- name: Set env
  shell: export LC_ALL="C"
  tags: start_mongod

- name: start mongod
  command: /usr/bin/mongod --config /etc/mongod-{{ item.name }}.conf
  with_items:
    - "{{ mongo_repl_set_list }}"
  tags: start_mongod

#- name: Create the mongodb configuration file
#  template: src=mongod.conf.j2 dest=/etc/mongod-{{ inventory_hostname }}.conf
#  delegate_to: '{{ item }}'
#  with_items: groups.replication_servers

#- name: Copy the keyfile for authentication
#  copy: src=secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400


#- name: Start the mongodb service
#  command: creates=/var/lock/subsys/mongod-{{ inventory_hostname }} /etc/init.d/mongod-{{ inventory_hostname }} start
#  delegate_to: '{{ item }}'
#  with_items: groups.replication_servers

#- name: Pause for a while
#  pause: seconds=20

#- name: Initialize the replication set
#  shell: /usr/bin/mongo --port "{{ mongod_port }}" /tmp/repset_init.js
